name: 'Mirroring To Gitee'

on: [push, delete]

jobs:
  to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:sculpta/data.git
          ssh_private_key:
            ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
