name: Backup To Gitee

on: [push]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Backup
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: "git@github.com:sculpta/data.git"
          SOURCE_BRANCH: "master"
          DESTINATION_REPO: "git@gitee.com:sculpta/data.git"
          DESTINATION_BRANCH: "master"
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
