name: Push to gitee

on: 
  push:
    branches:
      - master
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set SSH Key
      env: 
        SSH_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        SSH_KEY_PUB: ${{ secrets.GITEE_PUBLIC_KEY }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
        echo ${SSH_KEY} > ~/.ssh/id_rsa
        sed -i -e "s#\\\\n#\n#g" ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo ${SSH_KEY_PUB} > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
     
    - name: Push to gitee
      run: |
        git checkout master
        git remote add git@gitee.com:sculpta/data.git
        git push --set-upstream gitee master -f 
