name: 'Backup To Gitee'

on: [push, delete]

jobs:
  backup_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Backup
        uses: jenkins-zh/git-backup-actions@v0.0.1
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          TARGET_GIT: "git@gitee.com:sculpta/data.git"
